object Version {
    //App Level
    const val toolsBuildGradle = "7.4.2"
    const val kotlinGradle = "1.8.10"
    const val composeCompiler = "1.4.3"

    //Project Level
    const val accompanist = "0.29.1-alpha"
    const val activityCompose = "1.6.1"
    const val chucker = "3.5.2"
    const val coil = "2.2.2"
    const val composeAnimation = "1.3.3"
    const val composeFoundation = "1.3.1"
    const val composeMaterial3 = "1.0.1"
    const val composeRuntime = "1.3.3"
    const val composeUi = "1.3.3"
    const val constraintLayoutCompose = "1.0.1"
    const val coreKtx = "1.8.0"
    const val coreSplashScreen = "1.0.0"
    const val coroutines = "1.6.2"
    const val espresso = "3.4.0"
    const val extJUnit = "1.1.3"
    const val hilt = "2.42"
    const val hiltCompose = "1.0.0"
    const val jUnit = "4.13.2"
    const val kotlin = "1.6.10"
    const val lifecycle = "2.5.1"
    const val material = "1.7.0"
    const val moshi = "1.13.0"
    const val navigationCompose = "2.5.1"
    const val okHttp = "4.9.3"
    const val paging = "3.1.1"
    const val pagingCompose = "1.0.0-alpha16"
    const val retrofit = "2.9.0"
    const val reflect = "1.7.0"
    const val spotless = "6.10.0"
    const val test = "1.4.0"
    const val webkit = "1.4.0"
}